[workspace]
resolver = "3"
members = [
    "adapter-http/client",
    "adapter-http/server",
    "adapter-http/shared",
    "adapter-sqlite",
    "metric",
    "prelude",
    "server",
]

[workspace.package]
authors = ["Jeremie Drouet <jeremie.drouet@gmail.com>"]
license = "MIT"

[workspace.dependencies]
anyhow = { version = "1.0" }
myhomelab-adapter-sqlite = { path = "./adapter-sqlite" }
myhomelab-adapter-http-client = { path = "./adapter-http/client" }
myhomelab-adapter-http-server = { path = "./adapter-http/server" }
myhomelab-adapter-http-shared = { path = "./adapter-http/shared" }
myhomelab-metric = { path = "./metric" }
myhomelab-prelude = { path = "./prelude" }
serde = { version = "1.0" }
tokio = { version = "1.45" }
tracing = { version = "0.1" }
