[workspace]
resolver = "3"
members = ["adapter-sqlite", "inbound-http", "metric", "prelude"]

[workspace.package]
authors = ["Jeremie Drouet <jeremie.drouet@gmail.com>"]
license = "MIT"

[workspace.dependencies]
anyhow = { version = "1.0" }
myhomelab-inbound-http = { path = "./inbound-http" }
myhomelab-metric = { path = "./metric" }
myhomelab-prelude = { path = "./prelude" }
serde = { version = "1.0" }
tokio = { version = "1.45" }
tracing = { version = "0.1" }
