name: commit-lint

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  main:
    name: validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure that a scope must always be provided or not.
          requireScope: false
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern.
