name: debian package

on:
  workflow_call:
    inputs:
      release_tag:
        description: "Release tag to use"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to use"
        required: true
        type: string

env:
  RUSTFLAGS: "-Dwarnings"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - run: |
          docker build \
            --file .docker/debian.dockerfile \
            --platform linux/arm64 \
            --output type=local,dest=target/debian \
            --target deb-package .

      - name: upload the artifacts
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: "target/debian/myhomelab_*"
          tag_name: ${{ inputs.release_tag }}
