name: release-plz

permissions:
  pull-requests: write
  contents: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - uses: MarcoIeni/release-plz-action@v0.5
        id: release-plz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    outputs:
      releases: ${{ steps.release-plz.outputs.releases }}

  release-tags:
    runs-on: ubuntu-latest
    needs:
      - release-plz
    if: ${{ needs.release-plz.outputs.releases != '[]' && needs.release-plz.outputs.releases != '' }}
    steps:
      - name: parsing release-plz-output
        id: values
        run: |
          json_output=${{ needs.release-plz.oututs.releases }}
          myhomelab_tag=$(echo $json_output | jq -r '[.[] | select(.package_name == "myhomelab")] | map(.tag) | first')
          echo "myhomelab_tag=$myhomelab_tag" >> "$GITHUB_OUTPUT"
    outputs:
      myhomelab_tag: ${{ steps.values.outputs.myhomelab_tag }}

  trigger-build-releases:
    needs:
      - release-tags
    if: ${{ needs.release-tags.outputs.myhomelab_tag != 'null' }}
    uses: ./.github/workflows/debian-package.yml
    with:
      release_tag: ${{ needs.release-tags.outputs.myhomelab_tag }}
